track_parcel:
  fields:
    tracking_code:
      required: true
      example: "BTS_12345678901"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "BTS_12345678901"
      selector:
        text:
